### ISSUE TITLE
[TODO] push 전에 꼭 확인해야 할 사항들

### ISSUE THREAD

**Issue by Baek2back** [Baek2back/Cafe-W#1]
# Comparing Lighthouse results

- [ ] [호스팅 된 페이지](https://cafe-w.netlify.app/) Lighthouse Chrome Extension 이용해서 결과 추출하기.

- [ ] `localhost:port/page.html`에서 `npm run-script lighthouse` 명령어를 이용하여 `reports` 폴더에 생성되는 `pageName.html` 파일과 결과 비교하기

- [ ] 어떤 점을 개선했고, 어떤 점은 추가적으로 개선해야 할지 명시하기
